config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index"
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  post "/cart_items/:id/add" => "cart_items#add_quantity", as: :cart_item_add
  post "cart_items/:id/reduce" => "cart_items#reduce_quantity", as: :cart_item_reduce
  patch "/update_user/:id" => "users#update", as: :update_user
  get "admin" => "admin#show", as: :admin_dashboard
  get "admin/menu_items" => "admin#menu_items", as: :admin_menu_items
  get "admin/orders" => "admin#orders", as: :admin_orders
  get "admin/users" => "admin#users", as: :admin_users
  get "admin/categories" => "admin#category", as: :admin_categories
  delete "pending_orders" => "pending_orders#delivered", as: :pending_orders
  resources :users
  resources :orders
  resources :menu_items
  resources :menu_categories
  resources :cart_items
  resources :carts
  resources :order_items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :menu_items, through: :cart_items

  def sub_total
    sum = 0
    self.cart_items.each do |cart_item|
      sum += cart_item.total_price
    end
    return sum
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :menu_item

  def total_price
    self.quantity.to_i * self.menu_item.price.to_i
  end
end

app/models/menu_category.rb
class MenuCategory < ApplicationRecord
  has_many :menu_items
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu_category
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_many :pending_orders
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :menu_item
end

app/models/pending_order.rb
class PendingOrder < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: true }
  validates :password, presence: true, length: { minimum: 6 }, allow_blank: true
  validates :password, length: { minimum: 8 }
  has_many :orders
end

app/models/users.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :password, length: { minimum: 8 }
  has_many :orders
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/category.html.erb
<div class="container">
<div>
<h1 align="center">MENU_CATEGORIES  <h1>
</div>
<div>
<table class="table table-striped">
  <thead class="thead-dark">
  <tr>
    <th scope="col">id</th>
    <th scope="col">name</th>
    <th colspan="1"></th>
  </tr>
</thead>
<tbody>
<% @menu_categories.each do |category| %>
  <tr>
    <td><%= category.id %></td>
    <td><%= category.name %></td>
    <td><%= button_to "edit","#",class:"btn-primary "%></td>

  </tr>
<% end %>
</tbody>
</table>
</div>
<%= link_to "Back", admin_dashboard_path,class:"btn btn-primary btn-lg"%>
</div>

app/views/admin/menu_items.erb
<div>
<h1 align="center">MENU_ITEMS</h1>
</div>
<div>
<table class="table table-striped">
  <thead class="thead-dark">
  <tr>
    <th scope="col">id</h3></th>
    <th scope="col">name</h3></th>
    <th scope="col">category</h3></th>
    <th scope="col">price</h3></th>
    <th scope="col">description</h3></th>
     <th colspan="2"></th>
  </tr>
  </thead>
<tbody>
<% @menu_items.each do |item| %>
  <tr>
    <td><%= item.id %></td>
    <td><%= item.name %></td>
    <td><%= item.menu_category_id %></td>
    <td><%= item.price %></td>
    <td><%= item.description %></td>
    <td><%= link_to "edit", edit_menu_item_path(:id=>"#{item.id}"),class:"btn btn-primary btn-lg"%></td>
    <td><%= link_to "delete", menu_item_path(:id=>"#{item.id}"),method: :delete,class:"btn btn-primary btn-lg"%></td>
  </tr>
<% end %>
</tbody>
</table>
</div>
<%= link_to "Back", admin_dashboard_path,class:"btn btn-primary btn-lg"%>
<%= link_to "ADD ITEM", new_menu_item_path,class:"btn btn-primary btn-lg"%>

app/views/admin/orders.html.erb
<div>
<h1 align="center"> ALL Orders  <h1>
</div>
<div>
<table class="table table-striped">
  <thead class="thead-dark">
  <tr>
    <th scope="col">id</th>
    <th scope="col">Date</th>
    <th scope="col">UserId</th>
    <th scope="col">Total_price</th>
    <th scope="col">Delivered_at</th>
    <th colspan="1"></th>
  </tr>
</thead>
<tbody>
<% @orders.each do |order| %>
  <tr>
    <td><%= order.id %></td>
    <td><%= order.date %></td>
    <td><%= order.user_id %></td>
    <td><%= order.total_price %></td>
    <td><%= order.delivered_at %></td>
    <td><%= button_to "edit_status", pending_orders_path(:id => order.id), method: :delete %></td>

  </tr>
<% end %>
</tbody>
</table>
</div>
<%= link_to "Back", admin_dashboard_path,class:"btn btn-primary btn-lg" %>

app/views/admin/show.html.erb
<nav class="navbar navbar-dark bg-dark">
<a class="navbar-brand" href="#">ADMIN Board</a>
   <%= link_to "Menu_Items", admin_menu_items_path,class:"navbar-brand"%>
   <%= link_to "Orders", admin_orders_path,class:"navbar-brand"%>
   <%= link_to "Users", admin_users_path,class:"navbar-brand"%>
   <%= link_to "Menu_Categories", admin_categories_path,class:"navbar-brand"%>
   <%= link_to "signout", destroy_session_path, method: :delete,class:"navbar-brand"%>
</nav

app/views/admin/users.html.erb
<div class="container">
<h2 align="center"><b> ALL USERS  </b><h2>
</div>
<div>
<table class="table table-striped">
  <thead class="thead-dark">
  <tr>
    <th scope="col">id</th>
    <th scope="col">name</th>
    <th scope="col">email</th>
    <th colspan="1">
  </tr>
</thead>
<tbody>
<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= button_to " remove ", user_path(:id => user.id), method: :delete %></td>

  </tr>
<% end %>
</tbody>
</table>
</div>

<%= link_to "Back", admin_dashboard_path,class:"btn btn-primary btn-lg" %>
<%= link_to "Add", new_user_path,class:"btn btn-primary btn-lg" %>

app/views/layouts/_menu_category.html.erb
<div class="full-height scroll-bar">
  <ul id="slide-out" class="side-nav fixed rel">
    <h1 center>CATEGORIES</h1>
    <% @categories = @categories.nil? ? MenuCategory.all : @categories %>
    <% @categories.each do |category| %>
      <li><%= link_to category.name, menu_category_path(category) %></li>
   <% end %>

  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CafeteriaManagementSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<% if flash[:error] %>
  <div class="alert alert-danger"><%= flash[:error] %></div>
<% end %>
<% if flash[:success] %>
  <div class="alert alert-success"><%= flash[:success] %></div>
<% end %>
    <%= yield %>
  </body>
</html>