config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index"
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  post "/cart_items/:id/add" => "cart_items#add_quantity", as: :cart_item_add
  post "cart_items/:id/reduce" => "cart_items#reduce_quantity", as: :cart_item_reduce
  patch "/update_user/:id" => "users#update", as: :update_user
  get "admin" => "admin#show", as: :admin_dashboard
  get "admin/menu_items" => "admin#menu_items", as: :admin_menu_items
  get "admin/orders" => "admin#orders", as: :admin_orders
  get "admin/users" => "admin#users", as: :admin_users
  get "admin/categories" => "admin#category", as: :admin_categories
  delete "pending_orders" => "pending_orders#delivered", as: :pending_orders
  resources :users
  resources :orders
  resources :menu_items
  resources :menu_categories
  resources :cart_items
  resources :carts
  resources :order_items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :menu_items, through: :cart_items

  def sub_total
    sum = 0
    self.cart_items.each do |cart_item|
      sum += cart_item.total_price
    end
    return sum
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :menu_item

  def total_price
    self.quantity.to_i * self.menu_item.price.to_i
  end
end

app/models/menu_category.rb
class MenuCategory < ApplicationRecord
  has_many :menu_items
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu_category
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_many :pending_orders
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :menu_item
end

app/models/pending_order.rb
class PendingOrder < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: true }
  validates :password, presence: true, length: { minimum: 6 }, allow_blank: true
  validates :password, length: { minimum: 8 }
  has_many :orders
end

app/models/users.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :password, length: { minimum: 8 }
  has_many :orders
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :ensure_cart_created
  before_action :ensure_user_logged_in
  before_action :check_if_admin, only: [:create]

  def index
    @menu_items = MenuItem.all.order(created_at: :asc)
  end

  def show
    @menu_item = MenuItem.find (params[:id])
  end

  def new
    @menu_item = MenuItem.new
  end

  def edit
    @menu_item = MenuItem.find(params[:id])
  end

  def destroy
    menu_item = MenuItem.find(params[:id])
    if menu_item.destroy
      flash[:success] = "#{menu_item.name} has been deleted."
      redirect_to admin_dashboard_path
    else
      flash[:error] = "An error occured. Try deleting #{@menu_item.name} again."
    end
  end

  def update
    @menu_item = MenuItem.find(params[:id])
    @menu_item.menu_category_id = params[:menu_category_id],
                                  @menu_item.name = params[:name],
                                  @menu_item.price = params[:price],
                                  @menu_item.description = params[:description],
                                  @menu_item.menu_item_image = params[:image],
    if @menu_item.save
      flash[:success] = "Menu Item updated succesfully"
    else
      flash[:error] = "An error occured. Try adding #{@menu_item.name} again."
    end
    redirect_to admin_dashboard_path
  end

  def create
    menu_item = MenuItem.create!(
      menu_category_id: params[:menu_category_id],
      name: params[:name],
      price: params[:price],
      description: params[:description],
      menu_item_image: params[:image],
    )
    flash[:success] = "sucessfully item added!"
    #redirect to admin_dashboard_path
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/menu_items/edit.html.erb
<div class="container">
<p class="NewUsers-title">Update menu item</p>

<section class="UsersNew">
<%= form_with url: menu_item_path(:id=>"#{@menu_item.id}"), method: :put do |form|%>
<div class="Form-section">
<p class="FormInput-label">menu_category </p>
<%= form.text_field :menu_category_id, class:"Form-input" %>
</div>


<div class="Form-section">
<p class="FormInput-label">name: </p>
<%= form.text_field :name, class:"Form-input" %>
</div>
<div class="Form-section">
<p class="FormInput-label">description </p>
<%= form.text_field :description, class:"Form-input" %>
</div>

<div class="Form-section">
<p class="FormInput-label">price: </p>
<%= form.text_field :price, class:"Form-input" %>
</div>


<div class="Form-section">
<p class="FormInput-label">image </p>
<%= form.text_field :menu_item_image, class:"Form-input" %>
</div>

<div class="Form-section">
<%= form.submit "Add Item", class:"btn btn-primary btn-lg" %>
<%= link_to "Back", admin_dashboard_path,class:"btn btn-primary btn-lg"%>

</div>

<% end %>

</section>
</div>

app/views/menu_items/index.html.erb
<nav class="navbar navbar-pf-vertical">

 <div class="navbar-header">
    <button type="button" class="navbar-toggle">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    </nav>
<nav class="navbar navbar-light bg-dark">
<div class="col s9 full-height scroll-bar">
<h4><%=link_to "CATEGORIES",menu_categories_path ,class:"navbar-brand"%></h4>
<%=link_to " CART", cart_path(@current_cart) ,class:"navbar-brand"%>
<%=link_to " LOGOUT", destroy_session_path, method: :delete ,class:"navbar-brand"%>
<%=link_to " UPDATE PROFILE", edit_user_path(id: @current_user.id),class:"navbar-brand" %>
<%=link_to " MY PROFILE", user_path(@current_user.id) ,class:"navbar-brand"%>

</nav>

<section class="menu">
<div class="row full-height">
<div class="col s9 full-height scroll-bar">
<div class=menu>
<div class="row">
<% @menu_items = (!@category.nil?) ? @category.menu_items : @menu_items  %>
<% @menu_items.each do |menu_item| %>
<div class="col s12 m6 l4">

    <div class="card-image">
        <span class="activator">
        <p> <p>
        </span>
        <%= link_to(menu_item) do %>
        <%= image_tag(("food.jpg"), :width => "100%", :height => "auto", :style => "max-width:100%", :class => "image-thumb") %>
          <br>
          <span class="card-title"><%= menu_item.name %></span>
          <% end %>
    </div>
      <div class="card-action">
        <%= button_to "Add to cart", cart_items_path(menu_item_id: menu_item.id), method: :post %>

    </div>
  </div>
<% end %>
</div>
</div>
</div>
</div>
<section>
<%= bootstrap_icon "check",width:5,height:5,fill:"blue" %>

app/views/menu_items/new.html.erb
<div class="row container full-height scroll-bar">
<h4>Create new item<h4>

app/views/menu_items/show.html.erb
<div class="full-height scroll-bar">
  <div class="row">
    <div class="col s12 m6 l6 flow-text">
      <h3><%= @menu_item.name%></h3>
      <p><%= @menu_item.description %></p>
      <p>$<%=  @menu_item.price %></p>
    </div>

    <div class="container col s12 m6 l6">
      <%= image_tag(("coffee.jpg"), :width => "100%", :height => "auto", :style => "max-width:100%", :class => "image-thumb")%>
    </div>

  </div>

  </div>
</div>
<%= link_to "Back", menu_items_path,class:"btn btn-dark" %>