config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index"
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  post "/cart_items/:id/add" => "cart_items#add_quantity", as: :cart_item_add
  post "cart_items/:id/reduce" => "cart_items#reduce_quantity", as: :cart_item_reduce
  patch "/update_user/:id" => "users#update", as: :update_user
  get "admin" => "admin#show", as: :admin_dashboard
  get "admin/menu_items" => "admin#menu_items", as: :admin_menu_items
  get "admin/orders" => "admin#orders", as: :admin_orders
  get "admin/users" => "admin#users", as: :admin_users
  get "admin/categories" => "admin#category", as: :admin_categories
  delete "pending_orders" => "pending_orders#delivered", as: :pending_orders
  resources :users
  resources :orders
  resources :menu_items
  resources :menu_categories
  resources :cart_items
  resources :carts
  resources :order_items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :menu_items, through: :cart_items

  def sub_total
    sum = 0
    self.cart_items.each do |cart_item|
      sum += cart_item.total_price
    end
    return sum
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :menu_item

  def total_price
    self.quantity.to_i * self.menu_item.price.to_i
  end
end

app/models/menu_category.rb
class MenuCategory < ApplicationRecord
  has_many :menu_items
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu_category
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_many :pending_orders
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :menu_item
end

app/models/pending_order.rb
class PendingOrder < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: true }
  validates :password, presence: true, length: { minimum: 6 }, allow_blank: true
  validates :password, length: { minimum: 8 }
  has_many :orders
end

app/models/users.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :password, length: { minimum: 8 }
  has_many :orders
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :check_if_admin, only: [:show]

  def show
    @orders = Order.all
  end

  def menu_items
    @menu_items = MenuItem.all.order(created_at: :asc)
  end

  def orders
    @orders = Order.all
  end

  def users
    @users = User.all
  end

  def category
    @menu_categories = MenuCategory.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_admin, only: [:destroy]

  def new
    render "users/new"
  end

  def create
    existing_user = User.find_by_email(params[:email])
    if existing_user
      flash[:error] = "User Already Exists"
    else
      #@user = User.new(params[:user])
      user = User.create!(
        name: params[:name],
        email: params[:email],
        role: "user",
        password: params[:password],
      )
      # UserMailer.signup_confirmation(user).deliver
    end
    redirect_to "/"
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]
    @user.email = params[:email]
    @user.password_digest = params[:password_digest]
    @user.save
=begin
    if @user.save
      #render plain: user.name
      #flash[:success] = "Profile Successfully Updated"
    end
=end
    redirect_to menu_items_path
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    user = User.find(params[:id])
    User.destroy(user.id)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
<p class="NewUsers-title">Edit Profile!</p>

<%= @user.id%>
<section class="UsersNew">
<%= form_with url: user_path(:id=>"#{@user.id}"), method: :put do |form|%>
<div class="Form-section">
<p class="FormInput-label">Name: </p>
<%= form.text_field :name, class:"Form-input" %>
</div>

<div class="Form-section">
<p class="FormInput-label">Email: </p>
<%= form.email_field :email, class:"Form-input" %>
</div>

<div class="Form-section">
<p class="FormInput-label">Password: </p>
<%= form.password_field :password, class:"Form-input" %>
</div>

<div class="Form-section">
<%= form.submit "Save Changes!", class:"Form-submit btn btn-primary btn-lg" %>
<%= link_to "Back", menu_items_path,class:"btn btn-primary btn-lg"%>

</div>

<% end %>
</section>
</div>

app/views/users/new.html.erb
<div class="container">
<p class="NewUsers-title">Welcome new user!</p>

<section class="UsersNew">
<%= form_with url: users_path do |form|%>
<div class="Form-section">
<p class="FormInput-label">Name: </p>
<%= form.text_field :name, class:"Form-input" %>
</div>

<div class="Form-section">
<p class="FormInput-label">Email: </p>
<%= form.email_field :email, class:"Form-input" %>
</div>

<div class="Form-section">
<p class="FormInput-label">Password: </p>
<%= form.password_field :password, class:"Form-input" %>
</div>

<div class="Form-section">
<%= form.submit "Sign-up!", class:"Form-submit" %>
</div>

<% end %>
</section>
</div>

app/views/users/show.html.erb
<div class="container">


<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4"><%= @user.name %></h1>
   <p class="lead">role:<%= @user.role %> </p>
   </div>
</div>
 <%= link_to "Back", menu_items_path,class:"btn btn-primary btn-lg" %>