config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index"
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  post "/cart_items/:id/add" => "cart_items#add_quantity", as: :cart_item_add
  post "cart_items/:id/reduce" => "cart_items#reduce_quantity", as: :cart_item_reduce
  patch "/update_user/:id" => "users#update", as: :update_user
  get "admin" => "admin#show", as: :admin_dashboard
  get "admin/menu_items" => "admin#menu_items", as: :admin_menu_items
  get "admin/orders" => "admin#orders", as: :admin_orders
  get "admin/users" => "admin#users", as: :admin_users
  get "admin/categories" => "admin#category", as: :admin_categories
  delete "pending_orders" => "pending_orders#delivered", as: :pending_orders
  resources :users
  resources :orders
  resources :menu_items
  resources :menu_categories
  resources :cart_items
  resources :carts
  resources :order_items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :menu_items, through: :cart_items

  def sub_total
    sum = 0
    self.cart_items.each do |cart_item|
      sum += cart_item.total_price
    end
    return sum
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :menu_item

  def total_price
    self.quantity.to_i * self.menu_item.price.to_i
  end
end

app/models/menu_category.rb
class MenuCategory < ApplicationRecord
  has_many :menu_items
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu_category
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_many :pending_orders
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :menu_item
end

app/models/pending_order.rb
class PendingOrder < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: true }
  validates :password, presence: true, length: { minimum: 6 }, allow_blank: true
  validates :password, length: { minimum: 8 }
  has_many :orders
end

app/models/users.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :password, length: { minimum: 8 }
  has_many :orders
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:current_cart_id] = nil
    redirect_to menu_items_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<div class="container" >
<h1>MY CART</h1>
</div>

<div>
<table class="table table-striped">
<thead class="thead-dark">
<tr>
  <th scope="col">item</h3></th>
  <th scope="col">price</h3></th>
  <th scope="col">quantity</h3></th>
  <th scope="col">Total price</h3></th>
  <th colspan="3"></th>
</tr>
</thead>
<tbody>
<% @cart.cart_items.each do |cart_item| %>
<tr>
  <td><%= cart_item.menu_item.name%></td>

  <td><%= number_to_currency(cart_item.menu_item.price)%></td>
  <td><%= cart_item.quantity %> </td>
  <td><%= number_to_currency(cart_item.total_price)%></td>
   <td><%= button_to "+ ", cart_item_add_path(:id => cart_item), method: :post %></td>
  <td><%= button_to "-", cart_item_reduce_path(:id => cart_item), method: :post %></td>
      <td><%= button_to "Remove", cart_item_path(cart_item), method: :delete%></td>
</tr>
<% end %>
</tbody>
</table>
</div>

<h3>Sub total: <%= number_to_currency(@cart.sub_total) %></h3>
<%= button_to "Proceed to checkout", order_items_path ,method: :post%><br>
<%= link_to "Back", menu_items_path,class:"btn btn-dark" %>